# --- Шрифты и Оформление ---
font_family      Terminus (TTF)
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        10.0

# Отступы от краев окна (очень важно при hide_window_decorations)
window_padding_width 10

# --- Поведение ---
scrollback_lines 10000
url_prefixes     http https file ftp
strip_trailing_spaces always
focus_follows_mouse yes
linux_display_server wayland

# --- Уведомления и Звук ---
enable_audio_bell    no
window_alert_on_bell no
bell_on_tab          no

# --- Дизайн окна ---
hide_window_decorations yes
background_opacity      0.7
dim_opacity            0.75
# Цвет рамки активного окна в сплитах
active_border_color     #f99c55
inactive_border_color   #444444

# --- Табы ---
tab_bar_edge          bottom
tab_bar_style         powerline
tab_powerline_style   slanted
active_tab_foreground   #000
active_tab_background   #f99c55
inactive_tab_foreground #444
inactive_tab_background #222

# --- Управление окнами (Сплиты) ---
enabled_layouts        splits:split_axis=horizontal
allow_remote_control   no

# Бинды для создания окон
map ctrl+f5 launch --location=hsplit --cwd=current
map ctrl+f6 launch --location=vsplit --cwd=current
map ctrl+f7 layout_action rotate

# Перемещение окон (Shift + стрелки)
map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window downd

# Навигация между окнами (Ctrl + стрелки)
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down

# Быстрый релоад конфига без перезапуска Kitty
map ctrl+shift+f5 load_config_file
