# Предзагрузка изображения в память
preload = /home/chyntemir/Загрузки/Gemini_Generated_Image_1hx8ps1hx8ps1hx8.png

# Установка обоев на монитор eDP-1 (из твоего конфига niri)
wallpaper = eDP-1,/home/chyntemir/Загрузки/Gemini_Generated_Image_1hx8ps1hx8ps1hx8.png

# Выключаем IPC для экономии заряда (опционально)
# ipc = off
